### ISSUE TITLE
PAYMENT REQUEST PAGE: Show a summary and a link to WorldPay

### ISSUE THREAD

**Issue by grange85** [nationalarchives/letters-of-no-evidence#10]
* [x] Confirm page content
* [x] Retrieve necessary information from the InfoService database and format if necessary
* [x] Display a link to WorldPay
* [x] Integrate ASP application into HTML

**Comment by piriyapordes** [comment]
[payment request page and email.docx](https://github.com/nationalarchives/letters-of-no-evidence/files/1819790/payment.request.page.and.email.docx)

**Comment by piriyapordes** [comment]
![payment request page](https://user-images.githubusercontent.com/14074294/37531356-d2a3c7e4-2933-11e8-9229-05ab53e6fdbd.JPG)

@netdesignr Can we have the page content like so?
