### ISSUE TITLE
PAYMENT CONFIRMATION EMAIL: Confirm generic content

### ISSUE THREAD

**Issue by grange85** [nationalarchives/letters-of-no-evidence#11]
* [x] confirm email subject
* [x] confirm email body
* [x] confirm FROM address

**Comment by piriyapordes** [comment]
[Payment confirmation email.docx](https://github.com/nationalarchives/letters-of-no-evidence/files/1819425/Payment.confirmation.email.docx)

**Comment by piriyapordes** [comment]
@acurry00 is it possible to customise the email subject? At the moment it is: Information service - Payment confirmation [ref TNA123456]. Could we have it: The National Archives - Payment confirmation [ref TNA123456] ?

**Comment by piriyapordes** [comment]
@acurry00 also the current FROM address is: 'foifees@nationalarchives.gov.uk' - is it possible to have it coming from the Contact centre mailbox so users can respond directly if they need to?

**Comment by ACTNA** [comment]
I'll have a look into this now to see what we can do with the receipt email. Remember it is currently used by FOI enquiry fee requests so we might be limited to how much we can change.

**Comment by ACTNA** [comment]
It should be relatively straightforward to have separate FROM addresses and SUBJECTs for FOI Enquiry fee requests and for LONE fee requests.
But I don't have access to the database servers so cannot try it. I will get Carol to do this tomorrow when she is back in the office. (As well as strip out the XML tags from the enquiry summary.)

**Comment by piriyapordes** [comment]
Thanks @acurry00

**Comment by lizbryant** [comment]
@piriyapordes Do you want to begin the email with a salutation - 'Dear John Smith' ?
