### ISSUE TITLE
PAYMENT CONFIRMATION PAGE: Show a summary of payment

### ISSUE THREAD

**Issue by grange85** [nationalarchives/letters-of-no-evidence#14]
* [x] confirm page content
* [x] integrate ASP application into the HTML

**Comment by piriyapordes** [comment]
[Payment confirmation page and email.docx](https://github.com/nationalarchives/letters-of-no-evidence/files/1819777/Payment.confirmation.page.and.email.docx)

**Comment by lizbryant** [comment]
Hi Piriya.  This looks great - just needs consistent use of colons (or not using colons) throughout.

**Comment by piriyapordes** [comment]
thanks @lizbryant, have fixed those now 
[Payment confirmation page and email.docx](https://github.com/nationalarchives/letters-of-no-evidence/files/1851263/Payment.confirmation.page.and.email.docx)
