### ISSUE TITLE
INTRO PAGE: IA and service signposting

### ISSUE THREAD

**Issue by grange85** [nationalarchives/letters-of-no-evidence#3]

**Comment by piriyapordes** [comment]
![contact us page signposting](https://user-images.githubusercontent.com/14074294/38548386-8f574e3c-3ca9-11e8-91d7-6045ecec92bd.JPG)
@lizbryant would you mind taking a look at this and seeing if it's ok for a link to the LONE form from 'Contact us'?

**Comment by piriyapordes** [comment]
![contact us page signposting](https://user-images.githubusercontent.com/14074294/38548780-811976c8-3caa-11e8-9e88-f725c5e0f40c.JPG)
@lizbryant would you mind taking a look at this and seeing if it's ok please? - link from 'Contact us' page to LONE form

**Comment by lizbryant** [comment]
Yes, this looks fine.

**Comment by piriyapordes** [comment]
thanks!
