### ISSUE TITLE
PAYMENT REQUEST EMAIL: Confirm content for LNE request

### ISSUE THREAD

**Issue by grange85** [nationalarchives/letters-of-no-evidence#7]
* [x] confirm subject
* [x] confirm body

**Comment by piriyapordes** [comment]
[payment request page email.docx](https://github.com/nationalarchives/letters-of-no-evidence/files/1819924/payment.request.page.email.docx)

**Comment by piriyapordes** [comment]
Email subject: The National Archives - Request for search for no evidence of naturalisation
