### ISSUE TITLE
PAYMENT REQUEST EMAIL: Confirm content for generic payment

### ISSUE THREAD

**Issue by grange85** [nationalarchives/letters-of-no-evidence#8]
* [x] confirm subject
* [x] confirm body

**Comment by piriyapordes** [comment]
[generic payment request email.docx](https://github.com/nationalarchives/letters-of-no-evidence/files/1819880/generic.payment.request.email.docx)

**Comment by piriyapordes** [comment]
Email subject: The National Archives - Request for search for no evidence of naturalisation
