### ISSUE TITLE
PAYMENT REQUEST EMAIL: Send user email

### ISSUE THREAD

**Issue by grange85** [nationalarchives/letters-of-no-evidence#9]
* [x] email content
* [x] generate functionality to allow conditional formatting based on reference number
* [x] send email to the user

**Comment by ACTNA** [comment]
Can I have the new content for this email. Attached is a screenshot of current FOI Enquiry payment request email
![infoservcie_payment request email](https://user-images.githubusercontent.com/25226428/37645629-53905a1e-2c1f-11e8-92de-7b9766da5eb4.PNG)

**Comment by piriyapordes** [comment]
[generic payment request email.docx](https://github.com/nationalarchives/letters-of-no-evidence/files/1828707/generic.payment.request.email.docx)

**Comment by ACTNA** [comment]
Thanks Piriya. On the payment confimation email you have 'Summary of your enquiry' and on this one 'Enquiry summary:'. Is that alright or do you want them the same?
And under 'Enquiry summary:' we will have the below, yes?
Subject’s full name: Brian Smith
Alternative names: Brian Smythe
Date of birth: 1920
Date of death:
Country of birth: Italy
Your full name: Joe Jones
Email address: jjones@email.com
Postal address: 7 High Street, Richmond

**Comment by piriyapordes** [comment]
Thanks for spotting, @acurry00 - let's have 'Summary of your enquiry' on both if possible - better to be consistent.
And yes, the fields below that are correct.

**Comment by lizbryant** [comment]
Looks good!
